import { Button } from "@/components/ui/button";
import { ArrowRight, Sparkles } from "lucide-react";
import { Link } from "react-router-dom";
import heroFloorplan from "@/assets/hero-floorplan.jpg";

const Hero = () => {
  return (
    <section className="relative min-h-screen flex items-center justify-center overflow-hidden bg-gradient-hero">
      {/* Animated background blobs */}
      <div className="absolute inset-0 overflow-hidden pointer-events-none">
        <div className="absolute -top-1/2 -left-1/2 w-full h-full bg-primary/10 rounded-full blur-3xl animate-pulse" />
        <div className="absolute -bottom-1/2 -right-1/2 w-full h-full bg-secondary/10 rounded-full blur-3xl animate-pulse delay-1000" />
      </div>

      <div className="container mx-auto px-4 sm:px-6 lg:px-8 relative z-10">
        <div className="grid lg:grid-cols-2 gap-12 items-center">
          {/* Left content */}
          <div className="text-center lg:text-left space-y-8 animate-fade-in">
            <div className="inline-flex items-center gap-2 px-4 py-2 rounded-full bg-primary/10 border border-primary/20 text-primary text-sm font-medium">
              <Sparkles className="w-4 h-4" />
              AI-Powered Architectural Design
            </div>
            
            <h1 className="text-4xl sm:text-5xl lg:text-6xl xl:text-7xl font-bold leading-tight">
              Design Your
              <span className="block bg-gradient-primary bg-clip-text text-transparent">
                Dream Home
              </span>
              in Minutes
            </h1>
            
            <p className="text-lg sm:text-xl text-muted-foreground max-w-2xl">
              Professional 2D floor plans and stunning 3D house models, generated by AI. 
              Architect-grade quality, instant results, fully customizable to your needs.
            </p>
            
            <div className="flex flex-col sm:flex-row gap-4 justify-center lg:justify-start">
              <Link to="/auth">
                <Button variant="hero" size="xl" className="group w-full sm:w-auto">
                  Start Designing
                  <ArrowRight className="w-5 h-5 group-hover:translate-x-1 transition-transform" />
                </Button>
              </Link>
              <Button variant="outline" size="xl">
                View Examples
              </Button>
            </div>

            <div className="flex items-center gap-8 justify-center lg:justify-start pt-4">
              <div>
                <div className="text-2xl sm:text-3xl font-bold text-foreground">10,000+</div>
                <div className="text-sm text-muted-foreground">Designs Created</div>
              </div>
              <div className="h-12 w-px bg-border" />
              <div>
                <div className="text-2xl sm:text-3xl font-bold text-foreground">500+</div>
                <div className="text-sm text-muted-foreground">Happy Users</div>
              </div>
              <div className="h-12 w-px bg-border" />
              <div>
                <div className="text-2xl sm:text-3xl font-bold text-foreground">4.9★</div>
                <div className="text-sm text-muted-foreground">Rating</div>
              </div>
            </div>
          </div>

          {/* Right content - Hero Image */}
          <div className="relative animate-fade-in delay-300">
            <div className="relative rounded-2xl overflow-hidden shadow-glow">
              <img 
                src={heroFloorplan} 
                alt="Professional 2D floor plan with modern layout" 
                className="w-full h-auto object-cover"
              />
              <div className="absolute inset-0 bg-gradient-to-t from-background/80 via-transparent to-transparent" />
            </div>
            
            {/* Floating cards */}
            <div className="absolute -left-4 top-1/4 bg-card border border-border rounded-lg shadow-soft p-4 animate-fade-in delay-500 hidden sm:block">
              <div className="text-sm font-semibold text-foreground">2D Floor Plans</div>
              <div className="text-xs text-muted-foreground">AutoCAD quality</div>
            </div>
            
            <div className="absolute -right-4 bottom-1/4 bg-card border border-border rounded-lg shadow-soft p-4 animate-fade-in delay-700 hidden sm:block">
              <div className="text-sm font-semibold text-foreground">3D Models</div>
              <div className="text-xs text-muted-foreground">Photorealistic renders</div>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
};

export default Hero;